# LocalExecutor Apache Airflow.
# An simple structured to initialize the service Apache Airflow LocalExecutor.
# For workflows that are not at all complex and completely fast, it is recommended that you use LocalExecutor.

# -------------------------------- # -----------------------

version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: airflow-postgres
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    command: >
      postgres
      -c listen_addresses=*
      -c logging_collector=on
      -c log_destination=stderr
      -c max_connections=200
    networks:
      - airflow-net

# ------ DB Init ------

  initdb:
    image: padzx/airflow:latest
    container_name: airflow-initdb
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    entrypoint: ["/bin/bash", "-c"]
    command: ["airflow db init && sleep 5"]
    networks:
      - airflow-net

# ------ Apache Airflow Webserver ------

  webserver:
    image: padzx/airflow:latest
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres
      - initdb
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080
    ports:
      - "8080:8080" 
    volumes:
      - ./dags:/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    command: ["bash", "-c", "airflow webserver"]
    networks:
      - airflow-net

# ------ Apache Airflow Scheduler ------

  scheduler:
    image: padzx/airflow:latest
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    command: ["bash", "-c", "airflow scheduler"]
    networks:
      - airflow-net

# ------ Networks ------

networks:
  airflow-net:
    driver: bridge
