version: '3'
services:
  webserver:
    image: apache/airflow:2.9.1
    ports:
      - "8080:8080"  # Porta para acessar a interface web do Airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    # Outras configurações do serviço...
  scheduler:
    image: apache/airflow:2.9.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    # Outras configurações do serviço...
  # Outros serviços do Airflow, se houver...
