name: CI/CD for Apache Airflow on AWS

on:
  push:
    branches-ignore:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./ci/main.tf
        run: terraform init

      - name: Terraform Plan
        working-directory: ./ci/main.tf
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./ci/main.tf
        run: terraform apply -auto-approve tfplan

      - name: Run setup script
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@<EC2_INSTANCE_PUBLIC_IP> 'bash -s' < ./script/setup.sh
