name: CI/CD for Apache Airflow on AWS

on:
  push:
    branches-ignore:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./ci
        run: terraform init

      - name: Terraform Plan
        working-directory: ./ci
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./ci
        run: terraform apply -auto-approve tfplan

      - name: Get EC2 Instance IP
        id: ec2-ip
        run: |
          INSTANCE_ID=$(terraform output -raw ec2_instance_id)
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Run setup script
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$PUBLIC_IP 'bash -s' < ./script/setup.sh
