name: Build and Push Docker Image Apache Airflow

on:
  push:
    branches:
      - development
  
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker Airflow Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/docker-airflow/Dockerfile
          push: true
          tags: padzx/airflow:latest
          build-args: |
            VERSION=1.0
            AUTHOR="Gabriel Padilha <gabriel.padzx@outlook.com>"

      - name: Extract metadata for Docker Airflow Image
        id: meta_airflow
        uses: docker/metadata-action@v2
        with:
          images: padzx/airflow

      - name: Cleanup Docker images
        run: docker image prune -f
