#

name: Build Docker Images

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USR }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PWD }}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t padzx/python_airflow:latest .

      - name: Push Docker image
        run: docker push padzx/python_airflow:latest

      - name: Cleanup Docker images
        run: docker image prune -f
