name: Build and Push Docker Images

on:
  push:
    branches:
      - development

  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/docker-python/Dockerfile
          push: true
          tags: padzx/python_airflow:latest

      - name: Extract metadata for Docker JupyterLab Image
        id: meta_jupyterlab
        uses: docker/metadata-action@v2
        with:
          images: padzx/python_airflow

      - name: Cleanup Docker images
        run: docker image prune -f
