
name: Build Docker Images

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build Docker image
        run: docker build -t padzx/python_airflow:latest .

      - name: Push Docker image
        run: docker push padzx/python_airflow:latest

      - name: Cleanup Docker images
        run: docker image prune -f
